version: '3'

services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: core-mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: "core"
      MYSQL_PASSWORD: "core"
      MYSQL_DATABASE: "core"
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"