server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    active: local

gpt:
  uri: ${GPT_API_URI}
  apikey: ${GPT_API_KEY}
  model:
    recommend-variable-name: ${GPT_RECOMMEND_VARIABLE_NAME_MODEL}
    add-comment: ${GPT_ADD_COMMENT_MODEL}
    refactor-code: ${GPT_REFACTOR_CODE_MODEL}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    docExpansion: none
  paths-to-match:
    - /api/**
