version: 0.0
os: linux

# source 경로에 있는 파일을 EC2 인스턴스의 destination에 배포, 만약 해당 지점에 이미 파일들이 존재하면 overwrite
files:
  - source: /
    destination: /home/ubuntu/api-server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: run_new_was.sh
      timeout: 180
      runas: ubuntu
    - location: health_check.sh
      timeout: 180
      runas: ubuntu
    - location: switch.sh
      timeout: 180
      runas: ubuntu
