name: API Server Java CI with Gradle on DEV

# develop 브랜치에 pull_request 시에 동작
on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

# 동작 과정
jobs:
  build:
    
    # ubuntu 최신 버전에서 작동
    runs-on: ubuntu-latest

    steps:
      # 1) 워크플로우 실행 전 기본적으로 체크아웃 필요
      - name: checkout
        uses: actions/checkout@v3

      # 2) JDK 11버전 설치, 다른 JDK 버전을 사용하다면 수정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # 3) application.yml 세팅
      - name: setting application.yml
        run: |
          cd ./src/main/resources # resources 폴더로 이동
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./application-dev.yml
        shell: bash

      # 4) build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle # 실제 application build(-x 옵션을 통해 테스트는 제외)
        run: ./gradlew clean build -x test
        
    
